Update 电视盒子编译+IMG打包.yml

diff --git a/.github/workflows/电视盒子编译+IMG打包.yml b/.github/workflows/电视盒子编译+IMG打包.yml
--- a/.github/workflows/电视盒子编译+IMG打包.yml
+++ b/.github/workflows/电视盒子编译+IMG打包.yml
@@ -82,182 +82,186 @@ env:
 jobs:
   build:
     runs-on: ubuntu-22.04
-    if: github.event.repository.owner.id == github.event.sender.id
+    if: ${{ github.event.repository.owner.id }} == ${{ github.event.sender.id }}
 
     steps:
-    - name: Show system
-      run: |
-        echo -e "💬 Server information \n"
-        echo -e "💻 Server running on Ubuntu: [ Release: $(cat /etc/os-release | grep VERSION_CODENAME | cut -d '=' -f2) / Host: $(arch) ] \n"
-        echo -e "🧮 Server CPU configuration information: \n$(cat /proc/cpuinfo | grep name | cut -f2 -d: | uniq -c) \n"
-        echo -e "💾 Server memory usage: \n$(free -h) \n"
-        echo -e "🗃️ Server space usag: \n$(df -hT ${GITHUB_WORKSPACE}) \n"
+      - name: Checkout
+        uses: actions/checkout@v4
 
-    - name: Maximize build space
-      uses: easimon/maximize-build-space@master
-      with:
-        swap-size-mb: 1024
-        temp-reserve-mb: 512
-        root-reserve-mb: 4608
-        remove-dotnet: 'true'
-        remove-android: 'true'
-        remove-haskell: 'true'
-        remove-codeql: 'true'
+      - name: Free up space
+        uses: jlumbroso/free-disk-space@main
+        with:
+          tool-cache: false
+          android: true
+          dotnet: true
+          haskell: true
+          large-packages: true
+          docker-images: true
+          swap-storage: true      
+      
+      - name: Initialization environment
+        id: init
+        env:
+          DEBIAN_FRONTEND: noninteractive
+        run: |
+          docker rmi `docker images -q`
+          [[ -n "${AGENT_TOOLSDIRECTORY}" ]] && sudo rm -rf "${AGENT_TOOLSDIRECTORY}"
+          sudo rm -rf /usr/share/dotnet /etc/apt/sources.list.d /usr/local/lib/android 2>/dev/null
+          sudo -E apt-get -y update
+          sudo -E apt-get -y purge azure-cli ghc* zulu* llvm* firefox google* dotnet* powershell openjdk* mongodb* moby* || true
+          sudo -E apt-get -y install $(curl -fsSL https://is.gd/depend_ubuntu2204_openwrt)
+          sudo -E systemctl daemon-reload
+          sudo -E apt-get -y full-upgrade
+          sudo -E apt-get -y autoremove --purge
+          sudo -E apt-get clean
+          sudo mkdir -p /workdir
+          sudo chown ${USER}:${GROUPS} /workdir
+          sudo timedatectl set-timezone "${TZ}"
+          echo "status=success" >> ${GITHUB_OUTPUT}
 
-    - name: Checkout
-      uses: actions/checkout@v4
+      - name: Clone source code [ ${{ inputs.source_branch }} ]
+        id: codes
+        working-directory: /workdir
+        if: ${{ steps.init.outputs.status }} == 'success' && !cancelled()
+        run: |
+          # Set up compilation source code
+          if [[ "${{ inputs.source_branch }}" == *"openwrt"* ]]; then
+              REPO_URL="https://github.com/openwrt/openwrt"
+              REPO_BRANCH="main"
+              TAGS_NAME="official"
+          elif [[ "${{ inputs.source_branch }}" == *"lede"* ]]; then
+              REPO_URL="https://github.com/coolsnowwolf/lede"
+              REPO_BRANCH="master"
+              TAGS_NAME="lede"
+          elif [[ "${{ inputs.source_branch }}" == *"immortalwrt"* ]]; then
+              REPO_URL="https://github.com/immortalwrt/immortalwrt"
+              REPO_BRANCH="openwrt-23.05"
+              TAGS_NAME="immortalwrt"
+          elif [[ "${{ inputs.source_branch }}" == *"Lienol"* ]]; then
+              REPO_URL="https://github.com/Lienol/openwrt"
+              REPO_BRANCH="22.03"
+              TAGS_NAME="Lienol"
+          else
+              echo "Unknown source code repository."
+              exit 1
+          fi
 
-    - name: Init build dependencies
-      env:
-        DEBIAN_FRONTEND: noninteractive
-      run: |
-        docker rmi $(docker images -q) 2>/dev/null
-        sudo -E apt-get -qq update
-        sudo -E apt-get -qq install dwarves quilt llvm clang-13 lldb lld build-essential rsync asciidoc binutils bzip2 gawk gettext git libncurses5-dev \
-          patch python2.7 unzip zlib1g-dev lib32gcc-s1 libc6-dev-i386 subversion flex uglifyjs gcc-multilib p7zip-full msmtp libssl-dev texinfo libreadline-dev \
-          libglib2.0-dev xmlto qemu-utils upx-ucl libelf-dev autoconf automake libtool autopoint device-tree-compiler g++-multilib antlr3 gperf wget ccache curl \
-          swig coreutils vim nano python3 python3-dev python3-pip python3-ply python3-pyelftools lrzsz scons
-        pip3 install --user -U pylibfdt
-        sudo -E apt-get -qq autoremove --purge
-        sudo -E apt-get -qq clean
-        sudo -E git config --global user.name 'GitHub Actions' && git config --global user.email 'noreply@github.com'
-        sudo -E git config --global core.abbrev auto
-        df -h
-        
-    - name: Clone source code [ ${{ inputs.source_branch }} ]
-      id: codes
-      working-directory: /workdir
-      if: ${{ steps.init.outputs.status }} == 'success' && !cancelled()
-      run: |
-        # Set up compilation source code
-        if [[ "${{ inputs.source_branch }}" == *"openwrt"* ]]; then
-            REPO_URL="https://github.com/openwrt/openwrt"
-            REPO_BRANCH="main"
-            TAGS_NAME="official"
-        elif [[ "${{ inputs.source_branch }}" == *"lede"* ]]; then
-            REPO_URL="https://github.com/coolsnowwolf/lede"
-            REPO_BRANCH="master"
-            TAGS_NAME="lede"
-        elif [[ "${{ inputs.source_branch }}" == *"immortalwrt"* ]]; then
-            REPO_URL="https://github.com/immortalwrt/immortalwrt"
-            REPO_BRANCH="openwrt-23.05"
-            TAGS_NAME="immortalwrt"
-        elif [[ "${{ inputs.source_branch }}" == *"Lienol"* ]]; then
-            REPO_URL="https://github.com/Lienol/openwrt"
-            REPO_BRANCH="22.03"
-            TAGS_NAME="Lienol"
-        else
-            echo "Unknown source code repository."
-            exit 1
-        fi
-         # Clone source code
-        git clone -q --single-branch --depth=1 --branch=${REPO_BRANCH} ${REPO_URL} openwrt
-        ln -sf /workdir/openwrt ${GITHUB_WORKSPACE}/openwrt
-         # Set output information
-        echo "build_tag=OpenWrt_${TAGS_NAME}_${{ inputs.openwrt_storage }}_$(date +"%Y.%m")" >> ${GITHUB_OUTPUT}
-        echo -e "REPO_URL: [ ${REPO_URL} ]\nREPO_BRANCH: [ ${REPO_BRANCH} ]\nTAGS_NAME: [ ${TAGS_NAME} ]"
-        df -hT ${PWD}
-        echo "status=success" >> ${GITHUB_OUTPUT}
-    - name: Load custom feeds
-      run: |
-        [ -e files ] && mv files openwrt/files
-        [[ -f "${FEEDS_CONF}" ]] && cp -f ${FEEDS_CONF} openwrt/feeds.conf.default
-        chmod +x ${SCRIPT_SH}
-        cd openwrt/
-        ${GITHUB_WORKSPACE}/${SCRIPT_SH}
-    - name: Update feeds
-      run: |
-        chmod +x ${SRC_SH}
-        ${GITHUB_WORKSPACE}/${SRC_SH}
-        cd openwrt/ && ./scripts/feeds update -a
-    - name: Install feeds
-      run: cd openwrt/ && ./scripts/feeds install -a
-    - name: Load custom configuration
-      run: |
-        [[ -d "files" ]] && mv -f files openwrt/files
-        [[ -e "${CONFIG_FILE}" ]] && cp -f ${CONFIG_FILE} openwrt/.config
-                  
-    - name: Download package
-      id: package
-      run: |
-        cd openwrt/
-        make defconfig
-        make download -j8
-        find dl -size -1024c -exec ls -l {} \;
-        find dl -size -1024c -exec rm -f {} \;
-    - name: Compile the OpenWrt
-      id: compile
-      run: |
-        cd openwrt/
-        echo -e "$(nproc) thread compile"
-        make -j$(($(nproc) + 1)) V=s || make -j1 || make -j1 V=s
-        echo "======================="
-        echo "Space usage:"
-        echo "======================="
-        df -h
-        echo "======================="
-        du -h --max-depth=1 ./ --exclude=build_dir --exclude=bin
-        du -h --max-depth=1 ./build_dir
-        du -h --max-depth=1 ./bin
-        echo "status=success" >> ${GITHUB_OUTPUT}
+          # Clone source code
+          git clone -q --single-branch --depth=1 --branch=${REPO_BRANCH} ${REPO_URL} openwrt
+          ln -sf /workdir/openwrt ${GITHUB_WORKSPACE}/openwrt
 
-    - name: Clear server space
-      id: clean
-      if: ${{ steps.compile.outputs.status }} == 'success' && !cancelled()
-      run: |
-        # Clean up server space
-        cd openwrt/
-        mkdir output
-        cp -f bin/targets/*/*/*rootfs.tar.gz output/
-        cp -f .config output/config
-        rm -rf $(ls . | grep -v "^output$" | xargs) 2>/dev/null
-        # Generate sha256sum file
-        cd output/
-        for file in *; do [[ ! -d "${file}" ]] && sha256sum "${file}" >"${file}.sha"; done
-        # Set output information
-        df -hT ${PWD}
-        echo "status=success" >> ${GITHUB_OUTPUT}
+          # Set output information
+          echo "build_tag=OpenWrt_${TAGS_NAME}_${{ inputs.openwrt_storage }}_$(date +"%Y.%m")" >> ${GITHUB_OUTPUT}
+          echo -e "REPO_URL: [ ${REPO_URL} ]\nREPO_BRANCH: [ ${REPO_BRANCH} ]\nTAGS_NAME: [ ${TAGS_NAME} ]"
+          df -hT ${PWD}
+          echo "status=success" >> ${GITHUB_OUTPUT}
 
-    - name: Upload OpenWrt to Release
-      uses: ncipollo/release-action@main
-      if: ${{ steps.clean.outputs.status }} == 'success' && !cancelled()
-      with:
-        tag: ${{ steps.codes.outputs.build_tag }}
-        artifacts: openwrt/output/*
-        allowUpdates: true
-        removeArtifacts: false
-        replacesArtifacts: true
-        token: ${{ secrets.GH_TOKEN }}
+      - name: Load custom feeds
+        run: |
+          [ -e files ] && mv files openwrt/files
+          [[ -f "${FEEDS_CONF}" ]] && cp -f ${FEEDS_CONF} openwrt/feeds.conf.default
+          chmod +x ${SCRIPT_SH}
+          cd openwrt/
+          ${GITHUB_WORKSPACE}/${SCRIPT_SH}
 
-    - name: Packaging OpenWrt
-      if: ${{ steps.clean.outputs.status }} == 'success' && !cancelled()
-      uses: ophub/amlogic-s9xxx-openwrt@main
-      with:
-        openwrt_path: openwrt/output/*rootfs.tar.gz
-        openwrt_board: ${{ inputs.openwrt_board }}
-        openwrt_kernel: ${{ inputs.openwrt_kernel }}
-        auto_kernel: ${{ inputs.auto_kernel }}
-        kernel_repo: ${{ inputs.kernel_repo }}
-        kernel_usage: ${{ inputs.kernel_usage }}
-        builder_name: ${{ inputs.builder_name }}
-        gh_token: ${{ secrets.GH_TOKEN }}
+      - name: Update feeds
+        run: |
+          chmod +x ${SRC_SH}
+          ${GITHUB_WORKSPACE}/${SRC_SH}
+          cd openwrt/ && ./scripts/feeds update -a
 
-    - name: Upload the packaged OpenWrt
-      uses: ncipollo/release-action@main
-      if: ${{ env.PACKAGED_STATUS }} == 'success' && !cancelled()
-      with:
-        tag: ${{ steps.codes.outputs.build_tag }}
-        artifacts: ${{ env.PACKAGED_OUTPUTPATH }}/*
-        allowUpdates: true
-        removeArtifacts: false
-        replacesArtifacts: true
-        token: ${{ secrets.GH_TOKEN }}
-        body: |
-          ### N1 immortalwrt information
-          - Default IP: 192.168.2.200
-          - Default username: root
-          - Default password: none
-          ### Install to EMMC
-          - Login to OpenWrt → System → Amlogic Service → Install OpenWrt
-          ### OpenWrt Image Verification
-          - sha256sum
+      - name: Install feeds
+        run: cd openwrt/ && ./scripts/feeds install -a
+
+      - name: Load custom configuration
+        run: |
+          [[ -d "files" ]] && mv -f files openwrt/files
+          [[ -e "${CONFIG_FILE}" ]] && cp -f ${CONFIG_FILE} openwrt/.config
+                    
+      - name: Download package
+        id: package
+        run: |
+          cd openwrt/
+          make defconfig
+          make download -j8
+          find dl -size -1024c -exec ls -l {} \;
+          find dl -size -1024c -exec rm -f {} \;
+
+      - name: Compile the OpenWrt
+        id: compile
+        run: |
+          cd openwrt/
+          echo -e "$(nproc) thread compile"
+          make -j$(($(nproc) + 1)) V=s || make -j1 || make -j1 V=s
+          echo "======================="
+          echo "Space usage:"
+          echo "======================="
+          df -h
+          echo "======================="
+          du -h --max-depth=1 ./ --exclude=build_dir --exclude=bin
+          du -h --max-depth=1 ./build_dir
+          du -h --max-depth=1 ./bin
+          echo "status=success" >> ${GITHUB_OUTPUT}
+
+      - name: Clear server space
+        id: clean
+        if: ${{ steps.compile.outputs.status }} == 'success' && !cancelled()
+        run: |
+          # Clean up server space
+          cd openwrt/
+          mkdir output
+          cp -f bin/targets/*/*/*rootfs.tar.gz output/
+          cp -f .config output/config
+          rm -rf $(ls . | grep -v "^output$" | xargs) 2>/dev/null
+
+          # Generate sha256sum file
+          cd output/
+          for file in *; do [[ ! -d "${file}" ]] && sha256sum "${file}" >"${file}.sha"; done
+
+          # Set output information
+          df -hT ${PWD}
+          echo "status=success" >> ${GITHUB_OUTPUT}
+
+      - name: Upload OpenWrt to Release
+        uses: ncipollo/release-action@main
+        if: ${{ steps.clean.outputs.status }} == 'success' && !cancelled()
+        with:
+          tag: ${{ steps.codes.outputs.build_tag }}
+          artifacts: openwrt/output/*
+          allowUpdates: true
+          removeArtifacts: false
+          replacesArtifacts: true
+          token: ${{ secrets.GH_TOKEN }}
+
+      - name: Packaging OpenWrt
+        if: ${{ steps.clean.outputs.status }} == 'success' && !cancelled()
+        uses: ophub/amlogic-s9xxx-openwrt@main
+        with:
+          openwrt_path: openwrt/output/*rootfs.tar.gz
+          openwrt_board: ${{ inputs.openwrt_board }}
+          openwrt_kernel: ${{ inputs.openwrt_kernel }}
+          auto_kernel: ${{ inputs.auto_kernel }}
+          kernel_repo: ${{ inputs.kernel_repo }}
+          kernel_usage: ${{ inputs.kernel_usage }}
+          builder_name: ${{ inputs.builder_name }}
+          gh_token: ${{ secrets.GH_TOKEN }}
+
+      - name: Upload the packaged OpenWrt
+        uses: ncipollo/release-action@main
+        if: ${{ env.PACKAGED_STATUS }} == 'success' && !cancelled()
+        with:
+          tag: ${{ steps.codes.outputs.build_tag }}
+          artifacts: ${{ env.PACKAGED_OUTPUTPATH }}/*
+          allowUpdates: true
+          removeArtifacts: false
+          replacesArtifacts: true
+          token: ${{ secrets.GH_TOKEN }}
+          body: |
+            ### N1 immortalwrt information
+            - Default IP: 192.168.2.200
+            - Default username: root
+            - Default password: none
+            ### Install to EMMC
+            - Login to OpenWrt → System → Amlogic Service → Install OpenWrt
+            ### OpenWrt Image Verification
+            - sha256sum
